services:
  - type: web
    name: fingerprint-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ap:app
    runtime: python
    pythonVersion: 3.10.13
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
